import {
  RoadSegment,
  Incident,
  Vehicle,
  RouteOption,
  SystemAlert,
  LogisticsHub,
} from '../types';

// Map Coordinate System: 0-1000 width, 0-650 height
// Calibrated for Northeast India (Sikkim at top-left, Arunachal stretching top-right, Assam in central valley, Meghalaya below Assam, Nagaland/Manipur on east, Mizoram/Tripura at south-west/south).

export const MOCK_ROADS: RoadSegment[] = [
  {
    id: 'road-nh-6-barapani',
    name: 'NH-6 Guwahati — Shillong Expressway',
    highwayCode: 'NH-6',
    state: 'Meghalaya',
    district: 'Ri-Bhoi',
    startPoint: { name: 'Guwahati (Khanapara)', x: 380, y: 310, lat: 26.1158, lng: 91.8152 },
    endPoint: { name: 'Shillong (Barik)', x: 395, y: 380, lat: 25.5788, lng: 91.8933 },
    pathCoords: [
      { x: 380, y: 310 },
      { x: 384, y: 330 },
      { x: 388, y: 350 },
      { x: 392, y: 365 },
      { x: 395, y: 380 },
    ],
    status: 'high_risk',
    riskScore: 82,
    lengthKm: 98,
    elevationProfile: { minM: 55, maxM: 1496, avgSlopeDeg: 34 },
    currentWeather: {
      condition: 'Heavy Orographic Rainfall',
      rainfall24hMm: 168,
      rainfall7dMm: 540,
      windKmh: 42,
      saturationPct: 94,
    },
    pavementIndex: 42,
    historicalIncidentsCount: 14,
    affectedVehiclesCount: 6,
    aiExplanation:
      'Extreme 24h rainfall (168mm) saturated steep 34° weathered phyllite shale slope. Subsurface pore pressure exceeded shear threshold at km 48. High probability of recurring mass wasting.',
  },
  {
    id: 'road-nh-27-bypass',
    name: 'NH-27 East-West Corridor (Guwahati — Nagaon)',
    highwayCode: 'NH-27',
    state: 'Assam',
    district: 'Kamrup / Morigaon',
    startPoint: { name: 'Guwahati Jalukbari', x: 360, y: 300, lat: 26.1445, lng: 91.7362 },
    endPoint: { name: 'Nagaon Bypass Hub', x: 490, y: 295, lat: 26.3468, lng: 92.6841 },
    pathCoords: [
      { x: 360, y: 300 },
      { x: 400, y: 298 },
      { x: 445, y: 302 },
      { x: 490, y: 295 },
    ],
    status: 'safe',
    riskScore: 18,
    lengthKm: 122,
    elevationProfile: { minM: 48, maxM: 95, avgSlopeDeg: 4 },
    currentWeather: {
      condition: 'Intermittent Showers',
      rainfall24hMm: 32,
      rainfall7dMm: 120,
      windKmh: 18,
      saturationPct: 62,
    },
    pavementIndex: 88,
    historicalIncidentsCount: 2,
    affectedVehiclesCount: 12,
    aiExplanation:
      '4-lane paved all-weather concrete embankment elevated +2.5m above flood line. Drainage culverts operating at 45% discharge capacity. Safe for heavy multi-axle freight.',
  },
  {
    id: 'road-nh-29-naga',
    name: 'NH-29 Dimapur — Kohima Mountain Pass',
    highwayCode: 'NH-29',
    state: 'Nagaland',
    district: 'Kohima',
    startPoint: { name: 'Dimapur Freight Railhead', x: 570, y: 340, lat: 25.9068, lng: 93.7272 },
    endPoint: { name: 'Kohima Central Depot', x: 625, y: 375, lat: 25.6751, lng: 94.1086 },
    pathCoords: [
      { x: 570, y: 340 },
      { x: 588, y: 350 },
      { x: 605, y: 365 },
      { x: 625, y: 375 },
    ],
    status: 'moderate',
    riskScore: 58,
    lengthKm: 74,
    elevationProfile: { minM: 195, maxM: 1444, avgSlopeDeg: 28 },
    currentWeather: {
      condition: 'Dense Fog & Continuous Drizzle',
      rainfall24hMm: 74,
      rainfall7dMm: 280,
      windKmh: 24,
      saturationPct: 81,
    },
    pavementIndex: 61,
    historicalIncidentsCount: 8,
    affectedVehiclesCount: 4,
    aiExplanation:
      'Active soil creep detected on km 58 near Phesama bypass. Escort pilot convoys deployed. Single-lane bottleneck warning for vehicles >15 tonnes.',
  },
  {
    id: 'road-nh-10-teesta',
    name: 'NH-10 Siliguri — Rangpo — Gangtok Highway',
    highwayCode: 'NH-10',
    state: 'Sikkim',
    district: 'Pakyong',
    startPoint: { name: 'Sevoke Bridge / Siliguri', x: 120, y: 260, lat: 26.8906, lng: 88.4738 },
    endPoint: { name: 'Gangtok STNM Hospital', x: 140, y: 190, lat: 27.3389, lng: 88.6065 },
    pathCoords: [
      { x: 120, y: 260 },
      { x: 125, y: 235 },
      { x: 130, y: 215 },
      { x: 140, y: 190 },
    ],
    status: 'blocked',
    riskScore: 94,
    lengthKm: 114,
    elevationProfile: { minM: 120, maxM: 1750, avgSlopeDeg: 42 },
    currentWeather: {
      condition: 'Severe Cloudburst & River Surge',
      rainfall24hMm: 210,
      rainfall7dMm: 680,
      windKmh: 55,
      saturationPct: 98,
    },
    pavementIndex: 25,
    historicalIncidentsCount: 22,
    affectedVehiclesCount: 9,
    aiExplanation:
      'Teesta river gauge surpassed danger mark by 1.8m at km 28 (Birik Dara). 60m road deck washed out. Complete traffic suspension. Reroute via Lava-Algarah-Reshi pass.',
  },
  {
    id: 'road-nh-715-kaziranga',
    name: 'NH-715 Kaziranga Eco-Corridor Highway',
    highwayCode: 'NH-715',
    state: 'Assam',
    district: 'Golaghat',
    startPoint: { name: 'Jakhalabandha Junction', x: 495, y: 295, lat: 26.5782, lng: 93.0032 },
    endPoint: { name: 'Bokakhat Civil Center', x: 575, y: 285, lat: 26.6341, lng: 93.5932 },
    pathCoords: [
      { x: 495, y: 295 },
      { x: 525, y: 290 },
      { x: 550, y: 288 },
      { x: 575, y: 285 },
    ],
    status: 'moderate',
    riskScore: 62,
    lengthKm: 86,
    elevationProfile: { minM: 60, maxM: 85, avgSlopeDeg: 2 },
    currentWeather: {
      condition: 'Brahmaputra Backflow Flood Pulse',
      rainfall24hMm: 88,
      rainfall7dMm: 310,
      windKmh: 20,
      saturationPct: 89,
    },
    pavementIndex: 70,
    historicalIncidentsCount: 6,
    affectedVehiclesCount: 7,
    aiExplanation:
      'Brahmaputra flood water overflowing animal corridor bridges 2 & 4 by 25cm. Speed cap 20 km/h enforced to protect migrating wildlife & prevent engine water ingress.',
  },
  {
    id: 'road-nh-13-arunachal',
    name: 'NH-13 Trans-Arunachal Highway (Banderdewa — Pasighat)',
    highwayCode: 'NH-13',
    state: 'Arunachal Pradesh',
    district: 'Papum Pare',
    startPoint: { name: 'Banderdewa Checkpost', x: 520, y: 210, lat: 27.1264, lng: 93.8189 },
    endPoint: { name: 'Itanagar Civil Secretariat', x: 505, y: 190, lat: 27.0844, lng: 93.6053 },
    pathCoords: [
      { x: 520, y: 210 },
      { x: 512, y: 200 },
      { x: 505, y: 190 },
    ],
    status: 'safe',
    riskScore: 24,
    lengthKm: 38,
    elevationProfile: { minM: 110, maxM: 750, avgSlopeDeg: 19 },
    currentWeather: {
      condition: 'Overcast & Light Rain',
      rainfall24hMm: 42,
      rainfall7dMm: 160,
      windKmh: 15,
      saturationPct: 65,
    },
    pavementIndex: 82,
    historicalIncidentsCount: 3,
    affectedVehiclesCount: 5,
    aiExplanation:
      'Reinforced gabion retaining walls completed by BRO Project Vartak. Geo-textile slope mesh intact. High stability observed.',
  },
  {
    id: 'road-nh-102-manipur',
    name: 'NH-102 Imphal — Thoubal — Moreh Corridor',
    highwayCode: 'NH-102',
    state: 'Manipur',
    district: 'Imphal West / Tengnoupal',
    startPoint: { name: 'Imphal Medical Depot', x: 630, y: 440, lat: 24.817, lng: 93.9368 },
    endPoint: { name: 'Pallel — Moreh Border Link', x: 670, y: 510, lat: 24.2458, lng: 94.3045 },
    pathCoords: [
      { x: 630, y: 440 },
      { x: 645, y: 470 },
      { x: 670, y: 510 },
    ],
    status: 'safe',
    riskScore: 16,
    lengthKm: 110,
    elevationProfile: { minM: 780, maxM: 1200, avgSlopeDeg: 12 },
    currentWeather: {
      condition: 'Partly Cloudy',
      rainfall24hMm: 14,
      rainfall7dMm: 45,
      windKmh: 12,
      saturationPct: 48,
    },
    pavementIndex: 85,
    historicalIncidentsCount: 2,
    affectedVehiclesCount: 8,
    aiExplanation:
      'Optimal highway conditions. Security and medical supply convoy clear for unobstructed transit.',
  },
  {
    id: 'road-sh-3-bypass-meghalaya',
    name: 'State Highway 3 Bhoirymbong Alternate Bypass',
    highwayCode: 'SH-3',
    state: 'Meghalaya',
    district: 'Ri-Bhoi',
    startPoint: { name: 'Umiam Lake Junction', x: 385, y: 345, lat: 25.6601, lng: 91.9056 },
    endPoint: { name: 'Shillong Bypass Interchange', x: 420, y: 375, lat: 25.5901, lng: 91.9556 },
    pathCoords: [
      { x: 385, y: 345 },
      { x: 405, y: 355 },
      { x: 420, y: 375 },
    ],
    status: 'safe',
    riskScore: 22,
    lengthKm: 48,
    elevationProfile: { minM: 980, maxM: 1350, avgSlopeDeg: 14 },
    currentWeather: {
      condition: 'Passing Showers',
      rainfall24hMm: 44,
      rainfall7dMm: 170,
      windKmh: 20,
      saturationPct: 60,
    },
    pavementIndex: 84,
    historicalIncidentsCount: 1,
    affectedVehiclesCount: 11,
    aiExplanation:
      'AI Recommended Alternate Route. Gentle 14° slope, concrete culverts, zero active slips. Bypasses NH-6 Barapani blockage with +25 min delta.',
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'INC-2026-081',
    title: 'Major Landslide & Slope Collapse at Barapani Pass',
    type: 'landslide',
    severity: 'critical',
    roadId: 'road-nh-6-barapani',
    roadName: 'NH-6 Guwahati — Shillong Expressway',
    locationName: 'Km 48 Barapani S-Curve, Ri-Bhoi',
    milestoneKm: 'NH-6 Km 48.2',
    coords: { x: 388, y: 350, lat: 25.688, lng: 91.884 },
    reportedAt: '12 mins ago (08:30 IST)',
    reportedBy: {
      name: 'Insp. R. Sangma',
      badge: 'ML-PWD-904',
      department: 'Meghalaya PWD Highway Division',
    },
    description:
      'Massive 450-tonne earth and phyllite boulder slip collapsed across both northbound lanes following 168mm continuous rain. Trees down across overhead cables.',
    photoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80',
    weatherCondition: 'Heavy Downpour (168mm/24h)',
    rainfallMm: 168,
    affectedRoads: ['NH-6 Km 44 to 52', 'Old Guwahati Trunk Road'],
    affectedVehicleIds: ['NER-102', 'NER-115'],
    aiRiskScore: 92,
    aiPredictionReasoning:
      'Continuous 72h precipitation saturated geological slip plane. Slope shear safety factor dropped to 0.74 (<1.0 signifies failure). Residual slide risk: 84% within next 4 hours.',
    recommendedAction:
      'Immediately halt inbound vehicles at Jorabat Toll Plaza. Reroute essential medical freight NER-102 via Bhoirymbong SH-3 Bypass. Mobilize BRO JCB Dozer Unit from Umsning.',
    status: 'under_clearance',
    estimatedClearingTime: '3h 45m remaining',
    responseAgency: 'Border Roads Organisation (Project Setu) + NDRF 1st Bn',
  },
  {
    id: 'INC-2026-082',
    title: 'Flash Flood Overflow & Highway Submergence',
    type: 'flood',
    severity: 'high',
    roadId: 'road-nh-715-kaziranga',
    roadName: 'NH-715 Kaziranga Eco-Corridor',
    locationName: 'Burapahar Range, Golaghat',
    milestoneKm: 'NH-715 Km 112.5',
    coords: { x: 535, y: 289, lat: 26.612, lng: 93.245 },
    reportedAt: '38 mins ago (08:04 IST)',
    reportedBy: {
      name: 'Sub-Divisional Officer D. Borah',
      badge: 'AS-DIS-221',
      department: 'Assam State Disaster Management Authority',
    },
    description:
      'Diphlu river tributary breached right embankment. 0.45m swift-moving water sheet flowing over a 400m highway stretch. Heavy vehicles permitted at 15km/h escort only.',
    photoUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80',
    weatherCondition: 'Cloudburst in Upper Watershed (88mm)',
    rainfallMm: 88,
    affectedRoads: ['NH-715 Kohora — Bokakhat sector'],
    affectedVehicleIds: ['NER-214'],
    aiRiskScore: 78,
    aiPredictionReasoning:
      'Hydrological model projects river crest at +0.6m in 90 minutes. High danger of engine hydraulic stall for low-chassis supply vans.',
    recommendedAction:
      'Hold light supply vans at Jakhalabandha staging yard. Priority escorts for relief truck NER-214 using high-axle pilot tractor.',
    status: 'active',
    estimatedClearingTime: '5h 15m remaining',
    responseAgency: 'Assam Police Highway Patrol + SDRF Water Rescue Unit',
  },
  {
    id: 'INC-2026-083',
    title: 'Teesta River Toe Erosion & Road Deck Washout',
    type: 'road_damage',
    severity: 'critical',
    roadId: 'road-nh-10-teesta',
    roadName: 'NH-10 Siliguri — Gangtok Lifeline',
    locationName: 'Birik Dara, Kalimpong Border',
    milestoneKm: 'NH-10 Km 28.4',
    coords: { x: 128, y: 222, lat: 27.021, lng: 88.512 },
    reportedAt: '2 hours ago (06:40 IST)',
    reportedBy: {
      name: 'Capt. A. Chettri',
      badge: 'BRO-SW-118',
      department: 'Border Roads Organisation Task Force 752',
    },
    description:
      'Swollen Teesta River washed out 55 meters of reinforced retaining foundation. Road completely severed. No vehicular movement possible.',
    photoUrl: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&auto=format&fit=crop&q=80',
    weatherCondition: 'Torrential Glacier Melt Surge + Rain (210mm)',
    rainfallMm: 210,
    affectedRoads: ['NH-10 Entire Corridor from Melli to Teesta Bazaar'],
    affectedVehicleIds: ['NER-305'],
    aiRiskScore: 98,
    aiPredictionReasoning:
      'Complete structural loss. Rebuilding requires Bailey suspension bridge or temporary rock causeway. Risk of further collapse: 95%.',
    recommendedAction:
      'Activate Emergency Corridor via Lava — Gorubathan — Damdim. Divert all medical supply convoys immediately.',
    status: 'under_clearance',
    estimatedClearingTime: '48h 00m (Emergency Bailey Bridge assembly underway)',
    responseAgency: 'BRO Project Swastik & Indian Army Engineers Corps',
  },
  {
    id: 'INC-2026-084',
    title: 'Soil Creep & Mud Debris Influx',
    type: 'road_blockage',
    severity: 'medium',
    roadId: 'road-nh-29-naga',
    roadName: 'NH-29 Dimapur — Kohima Pass',
    locationName: 'Zubza Valley curve',
    milestoneKm: 'NH-29 Km 61.0',
    coords: { x: 598, y: 358, lat: 25.748, lng: 93.998 },
    reportedAt: '1 hour ago (07:42 IST)',
    reportedBy: {
      name: 'Officer K. Angami',
      badge: 'NL-POL-441',
      department: 'Nagaland Traffic Enforcement Unit',
    },
    description:
      'Continuous drizzle caused 20m wide mudflow across one lane. Earthmoving machinery deployed on site clearing debris. Alternating one-way traffic moving slowly.',
    photoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    weatherCondition: 'Continuous Drizzle & Dense Fog (74mm)',
    rainfallMm: 74,
    affectedRoads: ['NH-29 Phesama Bypass'],
    affectedVehicleIds: ['NER-410'],
    aiRiskScore: 54,
    aiPredictionReasoning:
      'Slope gradient moderate (28°). Soil saturation at 81%. Manageable with single-lane clearing operations.',
    recommendedAction:
      'Maintain one-way regulated convoy with 10-minute intervals. Keep heavy earthmover on standby.',
    status: 'under_clearance',
    estimatedClearingTime: '1h 30m remaining',
    responseAgency: 'Nagaland PWD + Local Traffic Police',
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh-102',
    code: 'NER-102',
    driverName: 'Bipul Sharma',
    driverPhone: '+91 98640 55123',
    operatorOrg: 'National Health Mission / ASDMA Supply Fleet',
    cargoType: 'Life-saving Pediatric Vaccines & Insulin (Cold Chain)',
    cargoCategory: 'CRITICAL',
    cargoWeightTons: 4.2,
    temperatureControlled: true,
    currentTempC: 3.8,
    targetTempC: 4.0,
    origin: 'Guwahati State Vaccine Store (Khanapara)',
    destination: 'Nongpoh Community Health Centre & Shillong Civil Hospital',
    currentLocationName: 'NH-6 Km 36 (approaching Jorabat)',
    coords: { x: 382, y: 325, lat: 26.045, lng: 91.845 },
    headingDeg: 165,
    speedKmh: 42,
    fuelPct: 82,
    eta: '2h 15m (Normal: 1h 20m, delayed by hazard)',
    routeRisk: 'high_risk',
    status: 'in_transit',
    activeRouteId: 'route-nh6-direct',
    alternateRouteAvailable: true,
    notes: 'HIGH PRIORITY: Cold chain battery backup has 5h 30m life. Prompt reroute advised to avoid Barapani landslide block.',
  },
  {
    id: 'veh-115',
    code: 'NER-115',
    driverName: 'Sanjay Thapa',
    driverPhone: '+91 94350 88219',
    operatorOrg: 'Meghalaya Emergency Medical Response Service',
    cargoType: 'Mobile Intensive Care Unit / Advanced Trauma Ventilators',
    cargoCategory: 'CRITICAL',
    cargoWeightTons: 3.5,
    temperatureControlled: false,
    origin: 'Guwahati Medical College (GMCH)',
    destination: 'NEIGRIHMS Multi-Speciality Trauma Ward, Shillong',
    currentLocationName: 'Umsning Outskirts',
    coords: { x: 390, y: 355, lat: 25.752, lng: 91.888 },
    headingDeg: 170,
    speedKmh: 18,
    fuelPct: 76,
    eta: '1h 45m',
    routeRisk: 'blocked',
    status: 'rerouted',
    activeRouteId: 'route-sh3-alternate',
    alternateRouteAvailable: false,
    notes: 'Green corridor active. Shifted to State Highway 3 Bhoirymbong Bypass. Police escort pilot vehicle engaged.',
  },
  {
    id: 'veh-214',
    code: 'NER-214',
    driverName: 'Manabendra Das',
    driverPhone: '+91 97060 12844',
    operatorOrg: 'Food Corporation of India (FCI Logistics)',
    cargoType: 'Baby Food, Fortified Rice & Emergency Rations',
    cargoCategory: 'HIGH',
    cargoWeightTons: 16.0,
    temperatureControlled: false,
    origin: 'FCI Central Silo, Amingaon (Guwahati)',
    destination: 'Kohima Central Disaster Food Reserve (Nagaland)',
    currentLocationName: 'NH-715 near Jakhalabandha',
    coords: { x: 508, y: 292, lat: 26.582, lng: 93.112 },
    headingDeg: 95,
    speedKmh: 28,
    fuelPct: 65,
    eta: '6h 10m',
    routeRisk: 'moderate',
    status: 'in_transit',
    activeRouteId: 'route-nh715-main',
    alternateRouteAvailable: true,
    notes: 'Escort convoy moving through Kaziranga flood stretch at 20 km/h. Vehicle clearance adequate.',
  },
  {
    id: 'veh-108',
    code: 'NER-108',
    driverName: 'Ramen Gogoi',
    driverPhone: '+91 94351 77209',
    operatorOrg: 'Assam Medical Services Corp',
    cargoType: 'Liquid Medical Oxygen Cylinders & Concentrators',
    cargoCategory: 'CRITICAL',
    cargoWeightTons: 9.8,
    temperatureControlled: false,
    origin: 'Guwahati Oxygen Generation Plant',
    destination: 'Silchar Medical College & Hospital (Cachar)',
    currentLocationName: 'NH-27 Dabaka Interchange',
    coords: { x: 470, y: 310, lat: 26.128, lng: 92.855 },
    headingDeg: 140,
    speedKmh: 54,
    fuelPct: 91,
    eta: '4h 30m',
    routeRisk: 'safe',
    status: 'in_transit',
    activeRouteId: 'route-nh27-express',
    alternateRouteAvailable: false,
    notes: 'Cruising safely on 4-lane NH-27 East-West Corridor. Optimal progress.',
  },
  {
    id: 'veh-305',
    code: 'NER-305',
    driverName: 'Tenzing Bhutia',
    driverPhone: '+91 97330 91822',
    operatorOrg: 'Sikkim Disaster Management Cell',
    cargoType: 'Mobile Water Purification Plant & Packaged IV Fluids',
    cargoCategory: 'HIGH',
    cargoWeightTons: 7.2,
    temperatureControlled: false,
    origin: 'Siliguri North-East Logistics Park',
    destination: 'Gangtok STNM Hospital',
    currentLocationName: 'Sevoke Diversion Junction',
    coords: { x: 122, y: 255, lat: 26.902, lng: 88.485 },
    headingDeg: 40,
    speedKmh: 0,
    fuelPct: 88,
    eta: 'Pending Reroute Decision',
    routeRisk: 'blocked',
    status: 'delayed',
    activeRouteId: 'route-nh10-direct',
    alternateRouteAvailable: true,
    notes: 'NH-10 blocked at Birik Dara. Staged at Sevoke. Awaiting AI Route Optimization confirmation via Lava-Reshi.',
  },
  {
    id: 'veh-410',
    code: 'NER-410',
    driverName: 'Hiren Borbaruah',
    driverPhone: '+91 99540 33418',
    operatorOrg: 'PWD Infrastructure Taskforce',
    cargoType: 'Modular Steel Bailey Bridge Panels & Fasteners',
    cargoCategory: 'NORMAL',
    cargoWeightTons: 22.4,
    temperatureControlled: false,
    origin: 'Guwahati Heavy Engineering Depot',
    destination: 'BRO Km 48 Barapani Restoration Site',
    currentLocationName: 'Byrnihat Weighbridge',
    coords: { x: 384, y: 332, lat: 26.065, lng: 91.865 },
    headingDeg: 165,
    speedKmh: 35,
    fuelPct: 58,
    eta: '1h 10m to staging',
    routeRisk: 'moderate',
    status: 'in_transit',
    activeRouteId: 'route-pwd-direct',
    alternateRouteAvailable: false,
    notes: 'Special heavy haul permit issued. Headed directly to incident site for emergency structural bridge erection.',
  },
];

export const MOCK_ROUTES_COMPARISON: {
  origin: string;
  destination: string;
  cargo: string;
  priority: string;
  routeA: RouteOption;
  routeB: RouteOption;
} = {
  origin: 'Guwahati State Vaccine & Medical Depot (Khanapara)',
  destination: 'Remote Healthcare Centre (Nongpoh / Shillong Civil)',
  cargo: 'Life-saving Pediatric Vaccines & Insulin (Cold-Chain)',
  priority: 'CRITICAL',
  routeA: {
    id: 'route-a-shortest',
    name: 'Route A: NH-6 Direct Mountain Highway (Shortest)',
    isRecommended: false,
    distanceKm: 98,
    etaMinutes: 320,
    etaFormatted: '5h 20m (with severe hazard delay)',
    safetyScore: 28,
    weatherRisk: 'Severe',
    disruptionProbabilityPct: 82,
    trafficLevel: 'Choked',
    highRiskSegmentsCount: 2,
    blockedSegmentsCount: 1,
    pathCoords: [
      { x: 380, y: 310 },
      { x: 384, y: 330 },
      { x: 388, y: 350 }, // incident point!
      { x: 392, y: 365 },
      { x: 395, y: 380 },
    ],
    summary: 'Shortest linear distance, but traverses high-gradient active landslide zone at Km 48.',
    aiJustification:
      'DO NOT DISPATCH CRITICAL CARGO. Active 450-tonne earth slip at Km 48. Saturated 34° slopes have 84% probability of recurring slope failure within 4 hours. Vehicle will encounter total stoppage.',
    pros: ['Lowest base physical distance (98 km)', 'Nominal transit time under dry conditions: 2h 10m'],
    cons: [
      'Active Landslide & Slope Collapse at Km 48 Barapani',
      'High Disruption Probability (82%)',
      'Cold chain battery depletion risk: 94%',
      'Single lane clearance creates 3h+ bottlenecks',
    ],
  },
  routeB: {
    id: 'route-b-recommended',
    name: 'Route B: SH-3 Bhoirymbong Bypass Corridor (AI Recommended)',
    isRecommended: true,
    distanceKm: 124,
    etaMinutes: 165,
    etaFormatted: '2h 45m (Guaranteed Flow)',
    safetyScore: 94,
    weatherRisk: 'Low',
    disruptionProbabilityPct: 12,
    trafficLevel: 'Light',
    highRiskSegmentsCount: 0,
    blockedSegmentsCount: 0,
    pathCoords: [
      { x: 380, y: 310 },
      { x: 385, y: 335 },
      { x: 405, y: 355 },
      { x: 420, y: 375 },
      { x: 395, y: 380 },
    ],
    summary: '+26 km longer distance, but 100% bypasses active landslide zone with newly paved concrete culverts.',
    aiJustification:
      'AI RECOMMENDED: Prioritizes SAFER and PRACTICAL routes over raw distance. SH-3 features engineered 14° gentle gradients, rock-anchored retaining walls, zero reported mass movements, and clear road deck. Conserves vaccine cold chain integrity.',
    pros: [
      'High Safety Score (94 / 100)',
      '100% bypasses Barapani landslide bottleneck',
      'Predictable arrival time: 2h 45m',
      'Cold chain battery safely maintained (>80% reserve)',
      'Designated Disaster Relief Green Corridor',
    ],
    cons: [
      '+26 km physical distance deviation',
      'Includes two toll pass checkpoints (auto-fastag whitelisted for emergency)',
    ],
  },
};

export const MOCK_SYSTEM_ALERTS: SystemAlert[] = [
  {
    id: 'ALT-101',
    title: 'Critical Landslide Risk: NH-6 Barapani Corridor Severed',
    severity: 'critical',
    timestamp: '14 mins ago',
    location: 'Km 48 Barapani, Ri-Bhoi, Meghalaya',
    roadName: 'NH-6 Guwahati — Shillong',
    affectedRoadIds: ['road-nh-6-barapani'],
    affectedVehicleIds: ['NER-102', 'NER-115'],
    recommendedAction: 'Immediate reroute of medical convoy NER-102 via State Highway 3 Bhoirymbong Bypass.',
    acknowledged: false,
    resolved: false,
    dispatchedToDriver: false,
  },
  {
    id: 'ALT-102',
    title: 'Flash Flood Warning: Brahmaputra Overwash on NH-715',
    severity: 'high',
    timestamp: '42 mins ago',
    location: 'Km 112 Burapahar Range, Kaziranga',
    roadName: 'NH-715 Kaziranga Eco-Corridor',
    affectedRoadIds: ['road-nh-715-kaziranga'],
    affectedVehicleIds: ['NER-214'],
    recommendedAction: 'Deploy high-clearance pilot escort and restrict vehicle speed to 20 km/h.',
    acknowledged: true,
    resolved: false,
    dispatchedToDriver: true,
  },
  {
    id: 'ALT-103',
    title: 'Complete Highway Deck Washout: NH-10 Teesta Corridor',
    severity: 'critical',
    timestamp: '2h 10m ago',
    location: 'Km 28 Birik Dara, Sikkim Border',
    roadName: 'NH-10 Siliguri — Gangtok Lifeline',
    affectedRoadIds: ['road-nh-10-teesta'],
    affectedVehicleIds: ['NER-305'],
    recommendedAction: 'Suspend all traffic. Route critical oxygen & IV transports via Lava — Reshi pass.',
    acknowledged: true,
    resolved: false,
    dispatchedToDriver: true,
  },
  {
    id: 'ALT-104',
    title: 'Soil Creep Advisory: NH-29 Naga Mountain Sector',
    severity: 'medium',
    timestamp: '3h 15m ago',
    location: 'Km 61 Zubza Valley, Kohima',
    roadName: 'NH-29 Dimapur — Kohima Pass',
    affectedRoadIds: ['road-nh-29-naga'],
    affectedVehicleIds: ['NER-410'],
    recommendedAction: 'Single-lane alternating convoys active. Limit multi-axle gross weight to 25T.',
    acknowledged: true,
    resolved: false,
    dispatchedToDriver: true,
  },
];

export const MOCK_LOGISTICS_HUBS: LogisticsHub[] = [
  {
    id: 'hub-ghy-central',
    name: 'Guwahati Central Logistics Port & GMCH Depot',
    type: 'warehouse',
    city: 'Guwahati',
    state: 'Assam',
    coords: { x: 375, y: 305, lat: 26.1445, lng: 91.7362 },
    capacityStatus: 'optimal',
    stockLevelPct: 92,
  },
  {
    id: 'hub-shillong-civil',
    name: 'Shillong Civil Hospital & NEIGRIHMS Trauma Hub',
    type: 'hospital',
    city: 'Shillong',
    state: 'Meghalaya',
    coords: { x: 395, y: 382, lat: 25.5788, lng: 91.8933 },
    capacityStatus: 'strained',
    stockLevelPct: 38, // needs urgent medicine replenishment!
  },
  {
    id: 'hub-tawang-border',
    name: 'Tawang Base Hospital & BRO Forward Depot',
    type: 'hospital',
    city: 'Tawang',
    state: 'Arunachal Pradesh',
    coords: { x: 260, y: 150, lat: 27.586, lng: 91.866 },
    capacityStatus: 'optimal',
    stockLevelPct: 78,
  },
  {
    id: 'hub-itanagar-ndrf',
    name: 'Itanagar 12th Bn NDRF Regional Emergency Center',
    type: 'ndrf_base',
    city: 'Itanagar',
    state: 'Arunachal Pradesh',
    coords: { x: 505, y: 190, lat: 27.0844, lng: 93.6053 },
    capacityStatus: 'optimal',
    stockLevelPct: 85,
  },
  {
    id: 'hub-kohima-depot',
    name: 'Kohima District Civil Supply Godown',
    type: 'warehouse',
    city: 'Kohima',
    state: 'Nagaland',
    coords: { x: 625, y: 375, lat: 25.6751, lng: 94.1086 },
    capacityStatus: 'strained',
    stockLevelPct: 44,
  },
  {
    id: 'hub-imphal-med',
    name: 'Imphal RIMS Regional Medical Depot',
    type: 'hospital',
    city: 'Imphal',
    state: 'Manipur',
    coords: { x: 630, y: 440, lat: 24.817, lng: 93.9368 },
    capacityStatus: 'optimal',
    stockLevelPct: 88,
  },
  {
    id: 'hub-aizawl-civil',
    name: 'Aizawl Civil Hospital & Disaster Store',
    type: 'hospital',
    city: 'Aizawl',
    state: 'Mizoram',
    coords: { x: 540, y: 530, lat: 23.7271, lng: 92.7176 },
    capacityStatus: 'optimal',
    stockLevelPct: 74,
  },
  {
    id: 'hub-agartala-hub',
    name: 'Agartala Integrated State Logistics Depot',
    type: 'warehouse',
    city: 'Agartala',
    state: 'Tripura',
    coords: { x: 420, y: 490, lat: 23.8315, lng: 91.2868 },
    capacityStatus: 'optimal',
    stockLevelPct: 82,
  },
  {
    id: 'hub-gangtok-stnm',
    name: 'STNM Multi-Speciality Hospital Gangtok',
    type: 'hospital',
    city: 'Gangtok',
    state: 'Sikkim',
    coords: { x: 140, y: 190, lat: 27.3389, lng: 88.6065 },
    capacityStatus: 'critical',
    stockLevelPct: 29, // awaiting water purification & IV fluid truck NER-305
  },
];

// District Disruption analytics
export const DISTRICT_ACCESSIBILITY_STATS = [
  { district: 'Kamrup Metro', state: 'Assam', accessibilityPct: 94, activeDisruptions: 0, criticalVehicles: 14 },
  { district: 'Ri-Bhoi', state: 'Meghalaya', accessibilityPct: 46, activeDisruptions: 2, criticalVehicles: 5 },
  { district: 'East Khasi Hills', state: 'Meghalaya', accessibilityPct: 62, activeDisruptions: 1, criticalVehicles: 4 },
  { district: 'Golaghat', state: 'Assam', accessibilityPct: 68, activeDisruptions: 1, criticalVehicles: 3 },
  { district: 'Kohima', state: 'Nagaland', accessibilityPct: 72, activeDisruptions: 1, criticalVehicles: 2 },
  { district: 'Pakyong', state: 'Sikkim', accessibilityPct: 32, activeDisruptions: 2, criticalVehicles: 3 },
  { district: 'Papum Pare', state: 'Arunachal Pradesh', accessibilityPct: 88, activeDisruptions: 0, criticalVehicles: 6 },
  { district: 'Imphal West', state: 'Manipur', accessibilityPct: 91, activeDisruptions: 0, criticalVehicles: 5 },
];

// Aliases for clean compatibility
export const MOCK_ROAD_SEGMENTS = MOCK_ROADS;
export const MOCK_ALERTS = MOCK_SYSTEM_ALERTS;

